# BASE DOCKER COMPOSE CONFIGURATION
# Shared settings across all environments
services:
  mysql:
    container_name: database
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Docker!23
      - MYSQL_DATABASE=ssw590
      - MYSQL_USER=express
      - MYSQL_PASSWORD=Express!23
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pDocker!23"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend

  grafana:
    container_name: reporting
    image: grafana/grafana
    ports:
      - '4000:3000'
    volumes:
      - grafana_volume:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_volume:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  mysql_volume:
  grafana_volume:
  prometheus_volume: